version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "TestEnvironment"
s3_bucket = "testbucket516845"
s3_prefix = "TestEnvironment"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
