name: PushWorkflow
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Build with Maven
        working-directory: ./HelloWorldFunction
        run: mvn clean install
      - uses: docker/build-push-action@v1
        with:
          username: "laujustas"
          password: "kcsbH93MVGzwcy4"
          repository: "laujustas/crop_test"
          tags: latest, ${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Zip Folder
        run: zip -r release.zip .
      - name: default deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: "AKIA2XHVB6KY3RKAHEEU"
          aws_secret_access_key: "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"
          aws_region: "us-east-1"
          function_name: crop-updated
          zip_file: release.zip
          memory_size: 128
          timeout: 10
          handler: helloworld.App::handleRequest
          role: arn:aws:iam::737100821169:role/CropTest-HelloWorldFunctionRole-KOFG859A2IDO
          runtime: java11

  invoke-remote:
    runs-on: ubuntu-latest
    needs: build
    if: contains(github.ref, 'master')
    steps:
      - name: Invoke deploy Lambda
        uses: gagoar/invoke-aws-lambda@master
        with:
          AWS_ACCESS_KEY_ID: "AKIA2XHVB6KY3RKAHEEU"
          AWS_SECRET_ACCESS_KEY: "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"
          FunctionName: CropTest-HelloWorldFunction-cS0jJYujneeL
          Payload: '"https://getwallpapers.com/wallpaper/full/2/5/4/727006-best-windows-xp-desktop-backgrounds-3840x2160.jpg"'