name: PushWorkflow
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Build with Maven
        working-directory: ./HelloWorldFunction
        run: mvn clean install
      - uses: docker/build-push-action@v1
        with:
          username: "laujustas"
          password: "kcsbH93MVGzwcy4"
          repository: "laujustas/crop_test"
          tags: latest, ${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v1
      - name: Zip Folder
        run: zip -r release.zip .
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: "AKIA2XHVB6KY3RKAHEEU"
          aws-secret-access-key: "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"
          aws-region: us-east-1
      - name: Deploy update
        run: aws lambda update-function-code --function-name=CropTest-HelloWorldFunction-cS0jJYujneeL --zip-file=fileb://release.zip

  invoke-remote:
    runs-on: ubuntu-latest
    needs: deploy
    if: contains(github.ref, 'master')
    steps:
      - name: Invoke deploy Lambda
        uses: gagoar/invoke-aws-lambda@master
        with:
          AWS_ACCESS_KEY_ID: "AKIA2XHVB6KY3RKAHEEU"
          AWS_SECRET_ACCESS_KEY: "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"
          FunctionName: CropTest-HelloWorldFunction-cS0jJYujneeL
          Payload: '"https://getwallpapers.com/wallpaper/full/2/5/4/727006-best-windows-xp-desktop-backgrounds-3840x2160.jpg"'