name: PushWorkflow
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Build with Maven
        working-directory: ./HelloWorldFunction
        run: mvn clean install
      - uses: docker/build-push-action@v1
        with:
          username: "laujustas"
          password: "kcsbH93MVGzwcy4"
          repository: "laujustas/crop_test:latest"
          tags: latest, ${{ github.sha }}
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: contains(github.ref, 'master')
    steps:
      - name: Invoke deploy Lambda
        uses: gagoar/invoke-aws-lambda@master
        with:
          AWS_ACCESS_KEY_ID: "AKIA2XHVB6KY3RKAHEEU"
          AWS_SECRET_ACCESS_KEY: "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"
          FunctionName: Crop_Test
          Payload: '{ "repo": "${{ github.repository }}", "sha": "${{ github.sha }}"}'